### ISSUE TITLE
Use the JSON interface of the Solidity compiler

### ISSUE THREAD

**Issue by axic** [Yakindu/solidity-ide#68] opened 2017-12-01 17:02 UTC
In https://github.com/Yakindu/solidity-ide/blob/master/plugins/com.yakindu.solidity.compiler/src/com/yakindu/solidity/compiler/builder/ I see that the command line interface is being used the text output is parsed for finding the binary, assembly, AST, etc.

I'd suggest considering the JSON interface of the compiler, which uses a structured JSON as an input and returns another JSON as an output. It can used via the commandline compiler: `solc --standard-json`, where the standard input expects the input and the standard output will contain the output.

For the documentation of the format please see https://solidity.readthedocs.io/en/develop/using-the-compiler.html#compiler-input-and-output-json-description

**Comment by flantony** [comment] 2017-12-08 14:44
From the given example i assume that solc consumes/produces JSON in typical "javascript-style". For example { name:"John" } instead of { "name":"John" }.  Tried to feed "valid" JSON to solc, which will produce parse errors. Therefore it is not possible to use common JSON libs like gson or jackson, since those will surround any key with " .

**Comment by axic** [comment] 2017-12-08 14:55
It should support any JSON accepted by jsoncpp, which claims to be in line with the RFC.

**Comment by flantony** [comment] 2017-12-18 10:09
Ok, spend some time on this again, without doing something else at the same time... and surprisingly it works as intended ;-) Refactored the entire usage of the compiler to make use of the JSON API. I was hoping to get rid of the "cutting" the formatted error message into pieces to find out the position of the error since it is very error prone. Apparently the "sourceLocation" field of errors are not mandatory and therefore not filled regularly, even when the formatted message contains the necessary information. 
I will close the issue for now. And see what we can do with the gained information. Thinking about a gas-estimation view.

**Comment by axic** [comment] 2017-12-18 10:17
> Apparently the "sourceLocation" field of errors are not mandatory and therefore not filled regularly, even when the formatted message contains the necessary information.

If the `formattedMessage` contains the location, while the other fields are not set that would be a bug. Do you have such an example?

**Comment by flantony** [comment] 2017-12-18 10:45
Compile something that yields a warning for "No visibility specified[...]"
I get:
```
{
  "component": "general",
  "formattedMessage": "Migrations.sol:13:5: Warning: No visibility specified. Defaulting to \"public\".\n    function Migrations()  {\r\n    ^\nSpanning multiple lines.\n",
  "message": "No visibility specified. Defaulting to \"public\".",
  "severity": "warning",
  "type": "Warning"
}
```
I expect:
```
{
  "component": "general",
  "sourceLocation" : {
        "file": "Migrations.sol",
        "start": x,
        "end": x+y 
  },
  "formattedMessage": "Migrations.sol:13:5: Warning: No visibility specified. Defaulting to \"public\".\n    function Migrations()  {\r\n    ^\nSpanning multiple lines.\n",
  "message": "No visibility specified. Defaulting to \"public\".",
  "severity": "warning",
  "type": "Warning"
}
```

where x is the beginning of the error relative to the beginning of the file and y is the length of the error.

**Comment by axic** [comment] 2017-12-18 11:09
Thanks, it seems like it is a bug. Created an issue for it.

**Comment by flantony** [comment] 2017-12-18 11:24
Thank you. I will keep an eye on this and further improve the integration asap

**Comment by axic** [comment] 2017-12-18 14:32
Fixed, will be part of the next release, but please test it with a local build if possible before the next release :)

**Comment by flantony** [comment] 2017-12-18 14:42
Great! Will integrate the new solc version in our next release.

**Closed** 2018-04-25 10:34 UTC
Labels: enhancement, refactoring
